// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"
#include "Vtop__Syms.h"
#include "Vtop___024root.h"

VL_ATTR_COLD void Vtop_cache_system_tl_top___eval_static__TOP__cache_system_tl_top(Vtop_cache_system_tl_top* vlSelf);
VL_ATTR_COLD void Vtop_cache_controller_nb___eval_static__TOP__cache_system_tl_top__cache_inst(Vtop_cache_controller_nb* vlSelf);
VL_ATTR_COLD void Vtop_tag_array__T80000_DB40_N10___eval_static__TOP__cache_system_tl_top__cache_inst__tag_array(Vtop_tag_array__T80000_DB40_N10* vlSelf);
VL_ATTR_COLD void Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array(Vtop_mem_model__M200_MB40* vlSelf);

VL_ATTR_COLD void Vtop___024root___eval_static(Vtop___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_static\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop_cache_system_tl_top___eval_static__TOP__cache_system_tl_top((&vlSymsp->TOP__cache_system_tl_top));
    Vtop_cache_controller_nb___eval_static__TOP__cache_system_tl_top__cache_inst((&vlSymsp->TOP__cache_system_tl_top__cache_inst));
    Vtop_tag_array__T80000_DB40_N10___eval_static__TOP__cache_system_tl_top__cache_inst__tag_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_static__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array));
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__clk_l__0 
        = vlSymsp->TOP__cache_system_tl_top.clk_l;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top.rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__clk_h__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.clk_h;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__clk_l__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.clk_l;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__rd_controller__DOT__cur_state__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.rd_controller__DOT__cur_state;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__wr_controller__DOT__busy_clk_l__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.wr_controller__DOT__busy_clk_l;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__rd_mem_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__rd_mem_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__rd_cam_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__rd_cam_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__erase_cam_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__erase_cam_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__wr_mem_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__wr_mem_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__genblk1__BRA__0__KET____DOT__stream_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__genblk1__BRA__0__KET____DOT__stream_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__genblk1__BRA__1__KET____DOT__stream_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__genblk1__BRA__1__KET____DOT__stream_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__genblk1__BRA__2__KET____DOT__stream_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__genblk1__BRA__2__KET____DOT__stream_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__f_unit__DOT____Vcellinp__genblk1__BRA__3__KET____DOT__stream_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.f_unit__DOT____Vcellinp__genblk1__BRA__3__KET____DOT__stream_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT____Vcellinp__latency_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst.d_array__DOT____Vcellinp__latency_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__tag_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__tag_array__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array.rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__tag_array____Vcellinp__latency_counter__rst_n__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array.__Vcellinp__latency_counter__rst_n;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array.clk;
    vlSelfRef.__Vtrigprevexpr___TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array__clk__0 
        = vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array.clk;
}

VL_ATTR_COLD void Vtop_cache_system_tl_top___eval_initial__TOP__cache_system_tl_top(Vtop_cache_system_tl_top* vlSelf);
VL_ATTR_COLD void Vtop_cache_controller_nb___eval_initial__TOP__cache_system_tl_top__cache_inst(Vtop_cache_controller_nb* vlSelf);
VL_ATTR_COLD void Vtop_tag_array__T80000_DB40_N10___eval_initial__TOP__cache_system_tl_top__cache_inst__tag_array(Vtop_tag_array__T80000_DB40_N10* vlSelf);
VL_ATTR_COLD void Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array(Vtop_mem_model__M200_MB40* vlSelf);

VL_ATTR_COLD void Vtop___024root___eval_initial(Vtop___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_initial\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop_cache_system_tl_top___eval_initial__TOP__cache_system_tl_top((&vlSymsp->TOP__cache_system_tl_top));
    Vtop_cache_controller_nb___eval_initial__TOP__cache_system_tl_top__cache_inst((&vlSymsp->TOP__cache_system_tl_top__cache_inst));
    Vtop_tag_array__T80000_DB40_N10___eval_initial__TOP__cache_system_tl_top__cache_inst__tag_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array));
    Vtop_mem_model__M200_MB40___eval_initial__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array));
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vtop___024root___dump_triggers__stl(Vtop___024root* vlSelf);
#endif  // VL_DEBUG

VL_ATTR_COLD void Vtop___024root___eval_triggers__stl(Vtop___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_triggers__stl\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.__VstlTriggered.setBit(0U, (IData)(vlSelfRef.__VstlFirstIteration));
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vtop___024root___dump_triggers__stl(vlSelf);
    }
#endif
}

void Vtop___024root___ico_sequent__TOP__0(Vtop___024root* vlSelf);
void Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__0(Vtop_cache_system_tl_top* vlSelf);
void Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__0(Vtop_cache_controller_nb* vlSelf);
void Vtop_tag_array__T80000_DB40_N10___ico_sequent__TOP__cache_system_tl_top__cache_inst__tag_array__0(Vtop_tag_array__T80000_DB40_N10* vlSelf);
void Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0(Vtop_mem_model__M200_MB40* vlSelf);
void Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__1(Vtop_cache_system_tl_top* vlSelf);
void Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__1(Vtop_cache_controller_nb* vlSelf);
void Vtop___024root___ico_sequent__TOP__1(Vtop___024root* vlSelf);
void Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__2(Vtop_cache_system_tl_top* vlSelf);
void Vtop_tag_array__T80000_DB40_N10___ico_sequent__TOP__cache_system_tl_top__cache_inst__tag_array__1(Vtop_tag_array__T80000_DB40_N10* vlSelf);
void Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1(Vtop_mem_model__M200_MB40* vlSelf);
void Vtop___024root___ico_sequent__TOP__2(Vtop___024root* vlSelf);
void Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__2(Vtop_cache_controller_nb* vlSelf);
void Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2(Vtop_mem_model__M200_MB40* vlSelf);
void Vtop_tag_array__T80000_DB40_N10___ico_sequent__TOP__cache_system_tl_top__cache_inst__tag_array__2(Vtop_tag_array__T80000_DB40_N10* vlSelf);
void Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__3(Vtop_cache_system_tl_top* vlSelf);
void Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__3(Vtop_cache_controller_nb* vlSelf);
void Vtop___024root___ico_sequent__TOP__3(Vtop___024root* vlSelf);

VL_ATTR_COLD void Vtop___024root___eval_stl(Vtop___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_stl\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if ((1ULL & vlSelfRef.__VstlTriggered.word(0U))) {
        Vtop___024root___ico_sequent__TOP__0(vlSelf);
        Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__0((&vlSymsp->TOP__cache_system_tl_top));
        Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst));
        Vtop_tag_array__T80000_DB40_N10___ico_sequent__TOP__cache_system_tl_top__cache_inst__tag_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__0((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array));
        Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__1((&vlSymsp->TOP__cache_system_tl_top));
        Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst));
        Vtop___024root___ico_sequent__TOP__1(vlSelf);
        Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__2((&vlSymsp->TOP__cache_system_tl_top));
        Vtop_tag_array__T80000_DB40_N10___ico_sequent__TOP__cache_system_tl_top__cache_inst__tag_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__1((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array));
        Vtop___024root___ico_sequent__TOP__2(vlSelf);
        Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array));
        Vtop_mem_model__M200_MB40___ico_sequent__TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array));
        Vtop_tag_array__T80000_DB40_N10___ico_sequent__TOP__cache_system_tl_top__cache_inst__tag_array__2((&vlSymsp->TOP__cache_system_tl_top__cache_inst__tag_array));
        Vtop_cache_system_tl_top___ico_sequent__TOP__cache_system_tl_top__3((&vlSymsp->TOP__cache_system_tl_top));
        Vtop_cache_controller_nb___ico_sequent__TOP__cache_system_tl_top__cache_inst__3((&vlSymsp->TOP__cache_system_tl_top__cache_inst));
        Vtop___024root___ico_sequent__TOP__3(vlSelf);
    }
}
