// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_CACHE_CONTROLLER_NB_H_
#define VERILATED_VTOP_CACHE_CONTROLLER_NB_H_  // guard

#include "verilated.h"
class Vtop_mem_model__M200_MB40;
class Vtop_tag_array__T80000_DB40_N10;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_cache_controller_nb final : public VerilatedModule {
  public:
    // CELLS
    Vtop_tag_array__T80000_DB40_N10* tag_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__0__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__1__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__2__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__3__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__4__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__5__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__6__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__7__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__8__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__9__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__10__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__11__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__12__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__13__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__14__KET____DOT__data_array;
    Vtop_mem_model__M200_MB40* __PVT__d_array__DOT__genblk4__BRA__15__KET____DOT__data_array;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_h,0,0);
        VL_IN8(clk_l,0,0);
        VL_IN8(rst_n,0,0);
        CData/*0:0*/ rd_controller__DOT__cur_state;
        CData/*0:0*/ wr_controller__DOT__busy_clk_l;
        CData/*0:0*/ f_unit__DOT____Vcellinp__rd_mem_counter__rst_n;
        CData/*0:0*/ f_unit__DOT____Vcellinp__rd_cam_counter__rst_n;
        CData/*0:0*/ f_unit__DOT____Vcellinp__erase_cam_counter__rst_n;
        CData/*0:0*/ f_unit__DOT____Vcellinp__wr_mem_counter__rst_n;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__0__KET____DOT__stream_counter__rst_n;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__1__KET____DOT__stream_counter__rst_n;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__2__KET____DOT__stream_counter__rst_n;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__3__KET____DOT__stream_counter__rst_n;
        CData/*0:0*/ d_array__DOT____Vcellinp__latency_counter__rst_n;
        VL_IN8(cfg_addr,7,0);
        VL_IN8(cfg_valid,0,0);
        VL_OUT8(cfg_ready,0,0);
        VL_IN8(in_byteen,3,0);
        VL_IN8(in_source,3,0);
        VL_IN8(in_opcode,2,0);
        VL_IN8(in_valid,0,0);
        VL_IN8(in_write,0,0);
        VL_OUT8(in_ready,0,0);
        VL_OUT8(out_source,3,0);
        VL_OUT8(out_opcode,2,0);
        VL_OUT8(out_valid,0,0);
        VL_IN8(out_ready,0,0);
        VL_OUT8(read_valid,0,0);
        VL_IN8(read_ready,0,0);
        VL_OUT8(write_byteen,3,0);
        VL_OUT8(write_valid,0,0);
        VL_IN8(write_ready,0,0);
        CData/*3:0*/ fsm_way;
        CData/*0:0*/ write_through;
        CData/*0:0*/ prefetch;
        CData/*0:0*/ secure_request;
        CData/*3:0*/ low_bound;
        CData/*3:0*/ high_bound;
        CData/*0:0*/ load;
        CData/*0:0*/ req_valid;
        CData/*0:0*/ req_done;
        CData/*0:0*/ req_ready;
        CData/*0:0*/ cache_write_valid;
        CData/*0:0*/ cache_write_ready;
        CData/*0:0*/ req_done_sync_0;
        CData/*0:0*/ req_done_sync_1;
        CData/*0:0*/ req_done_sync_2;
        CData/*0:0*/ req_done_pulse;
        CData/*0:0*/ fsm_valid;
        CData/*0:0*/ fsm_rw;
        CData/*0:0*/ tag_ready;
        CData/*0:0*/ fsm_accessed;
        CData/*0:0*/ fsm_hit;
        CData/*0:0*/ return_valid;
        CData/*0:0*/ return_ready;
        CData/*0:0*/ trans_valid;
        CData/*0:0*/ trans_done;
        CData/*0:0*/ fsm_in_ready;
        CData/*3:0*/ fsm_out_source;
        CData/*2:0*/ fsm_out_opcode;
        CData/*0:0*/ fsm_out_valid;
        CData/*0:0*/ fsm_out_ready;
        CData/*0:0*/ mshr_fin_valid;
        CData/*0:0*/ mshr_fin_is_hit;
    };
    struct {
        CData/*1:0*/ mshr_fin_id;
        CData/*0:0*/ miss_trigger;
        CData/*0:0*/ mshr_alloc_ready;
        CData/*1:0*/ mshr_alloc_id;
        CData/*0:0*/ mshr_alloc_match;
        CData/*1:0*/ mshr_alloc_match_id;
        CData/*0:0*/ mshr_deq_valid;
        CData/*3:0*/ mshr_deq_source;
        CData/*2:0*/ mshr_deq_opcode;
        CData/*1:0*/ mshr_deq_id;
        CData/*0:0*/ mshr_deq_ready;
        CData/*0:0*/ mshr_do_alloc;
        CData/*1:0*/ miss_mshr_id;
        CData/*0:0*/ __Vcellinp__c_fsm__in_valid;
        CData/*0:0*/ hit_out_valid;
        CData/*0:0*/ refill_out_valid;
        CData/*3:0*/ refill_word_idx;
        CData/*0:0*/ valid;
        CData/*0:0*/ write;
        CData/*0:0*/ write_all;
        CData/*3:0*/ byteen_keep;
        CData/*3:0*/ fsm_word_idx;
        CData/*0:0*/ g_word_transfer__BRA__0__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__0__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__0__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__0__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__1__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__1__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__1__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__1__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__2__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__2__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__2__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__2__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__3__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__3__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__3__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__3__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__4__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__4__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__4__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__4__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__5__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__5__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__5__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__5__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__6__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__6__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__6__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__6__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__7__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__7__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__7__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__7__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__8__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__8__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__8__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__8__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__9__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__9__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__9__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__9__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__10__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__10__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
    };
    struct {
        CData/*0:0*/ g_word_transfer__BRA__10__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__10__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__11__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__11__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__11__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__11__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__12__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__12__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__12__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__12__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__13__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__13__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__13__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__13__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__14__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__14__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__14__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__14__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__15__KET____DOT__g_byte_merge__BRA__0__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__15__KET____DOT__g_byte_merge__BRA__1__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__15__KET____DOT__g_byte_merge__BRA__2__KET____DOT__byte_wr_en;
        CData/*0:0*/ g_word_transfer__BRA__15__KET____DOT__g_byte_merge__BRA__3__KET____DOT__byte_wr_en;
        CData/*0:0*/ reg_file__DOT__clk;
        CData/*0:0*/ reg_file__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__in_valid;
        CData/*0:0*/ reg_file__DOT__in_ready;
        CData/*5:0*/ reg_file__DOT__in_addr;
        CData/*0:0*/ reg_file__DOT__write_through;
        CData/*0:0*/ reg_file__DOT__prefetch;
        CData/*0:0*/ reg_file__DOT__secure_request;
        CData/*3:0*/ reg_file__DOT__low_bound;
        CData/*3:0*/ reg_file__DOT__high_bound;
        CData/*0:0*/ reg_file__DOT__load;
        CData/*0:0*/ reg_file__DOT__set_write;
        CData/*0:0*/ reg_file__DOT__set_secure;
        CData/*0:0*/ reg_file__DOT__set_low_bound;
        CData/*0:0*/ reg_file__DOT__set_high_bound;
        CData/*0:0*/ reg_file__DOT__set_prefetch;
        CData/*0:0*/ reg_file__DOT__set_load_val_0;
        CData/*0:0*/ reg_file__DOT__set_load_val_1;
        CData/*0:0*/ reg_file__DOT__set_load_val_2;
        CData/*0:0*/ reg_file__DOT__set_load_val_3;
        CData/*0:0*/ reg_file__DOT__set_load_val_4;
        CData/*0:0*/ reg_file__DOT__set_load_val_5;
        CData/*0:0*/ reg_file__DOT__set_load_val;
        CData/*5:0*/ reg_file__DOT__addr;
        CData/*0:0*/ reg_file__DOT__set_load_val_prev;
        CData/*0:0*/ reg_file__DOT__load_val_edge__DOT__clk;
        CData/*0:0*/ reg_file__DOT__load_val_edge__DOT__rst;
        CData/*0:0*/ reg_file__DOT__load_val_edge__DOT__signal_in;
        CData/*0:0*/ reg_file__DOT__load_val_edge__DOT__signal_out;
        CData/*0:0*/ reg_file__DOT__load_val_edge__DOT__ff_m1;
        CData/*0:0*/ reg_file__DOT__D_FF_write__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_write__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_write__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_write__DOT__din;
        CData/*0:0*/ reg_file__DOT__D_FF_write__DOT__dout;
        CData/*0:0*/ reg_file__DOT__D_FF_write__DOT__data;
        CData/*0:0*/ reg_file__DOT__D_FF_secure__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_secure__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_secure__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_secure__DOT__din;
        CData/*0:0*/ reg_file__DOT__D_FF_secure__DOT__dout;
        CData/*0:0*/ reg_file__DOT__D_FF_secure__DOT__data;
    };
    struct {
        CData/*0:0*/ reg_file__DOT__D_FF_l_b__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_l_b__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_l_b__DOT__set;
        CData/*3:0*/ reg_file__DOT__D_FF_l_b__DOT__din;
        CData/*3:0*/ reg_file__DOT__D_FF_l_b__DOT__dout;
        CData/*3:0*/ reg_file__DOT__D_FF_l_b__DOT__data;
        CData/*0:0*/ reg_file__DOT__D_FF_h_b__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_h_b__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_h_b__DOT__set;
        CData/*3:0*/ reg_file__DOT__D_FF_h_b__DOT__din;
        CData/*3:0*/ reg_file__DOT__D_FF_h_b__DOT__dout;
        CData/*3:0*/ reg_file__DOT__D_FF_h_b__DOT__data;
        CData/*0:0*/ reg_file__DOT__D_FF_pf__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_pf__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_pf__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_pf__DOT__din;
        CData/*0:0*/ reg_file__DOT__D_FF_pf__DOT__dout;
        CData/*0:0*/ reg_file__DOT__D_FF_pf__DOT__data;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_0__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_0__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_0__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_1__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_1__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_1__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_2__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_2__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_2__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_3__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_3__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_3__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_4__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_4__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_4__DOT__set;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_5__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_5__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_l_va_5__DOT__set;
        CData/*7:0*/ reg_file__DOT__D_FF_l_va_5__DOT__din;
        CData/*7:0*/ reg_file__DOT__D_FF_l_va_5__DOT__dout;
        CData/*7:0*/ reg_file__DOT__D_FF_l_va_5__DOT__data;
        CData/*0:0*/ reg_file__DOT__D_FF_addr__DOT__clk;
        CData/*0:0*/ reg_file__DOT__D_FF_addr__DOT__rst_n;
        CData/*0:0*/ reg_file__DOT__D_FF_addr__DOT__set;
        CData/*5:0*/ reg_file__DOT__D_FF_addr__DOT__din;
        CData/*5:0*/ reg_file__DOT__D_FF_addr__DOT__dout;
        CData/*5:0*/ reg_file__DOT__D_FF_addr__DOT__data;
        CData/*0:0*/ rd_controller__DOT__clk_l;
        CData/*0:0*/ rd_controller__DOT__clk_h;
        CData/*0:0*/ rd_controller__DOT__rst_n;
        CData/*0:0*/ rd_controller__DOT__cache_read_valid;
        CData/*0:0*/ rd_controller__DOT__cache_read_done;
        CData/*0:0*/ rd_controller__DOT__cache_read_ready;
        CData/*0:0*/ rd_controller__DOT__mem_read_valid;
        CData/*0:0*/ rd_controller__DOT__mem_read_done;
        CData/*0:0*/ rd_controller__DOT__next_state;
        CData/*0:0*/ rd_controller__DOT__mem_read_o_valid;
        CData/*3:0*/ rd_controller__DOT__counter_wire;
        CData/*0:0*/ rd_controller__DOT__counter_done;
        CData/*0:0*/ rd_controller__DOT__all_beats_received;
        CData/*3:0*/ rd_controller__DOT__data_slot_idx;
        CData/*0:0*/ rd_controller__DOT__counter_offset_inst__DOT__clk;
        CData/*0:0*/ rd_controller__DOT__counter_offset_inst__DOT__rst_n;
        CData/*0:0*/ rd_controller__DOT__counter_offset_inst__DOT__start;
        CData/*4:0*/ rd_controller__DOT__counter_offset_inst__DOT__counter;
        CData/*0:0*/ rd_controller__DOT__counter_offset_inst__DOT__done;
    };
    struct {
        CData/*0:0*/ rd_controller__DOT__counter_offset_inst__DOT__done_w;
        CData/*0:0*/ wr_controller__DOT__clk_l;
        CData/*0:0*/ wr_controller__DOT__clk_h;
        CData/*0:0*/ wr_controller__DOT__rst_n;
        CData/*0:0*/ wr_controller__DOT__cache_write_valid;
        CData/*3:0*/ wr_controller__DOT__cache_write_byteen;
        CData/*0:0*/ wr_controller__DOT__cache_write_ready;
        CData/*0:0*/ wr_controller__DOT__mem_write_valid;
        CData/*3:0*/ wr_controller__DOT__mem_write_byteen;
        CData/*0:0*/ wr_controller__DOT__mem_write_done;
        CData/*0:0*/ wr_controller__DOT__cur_state;
        CData/*0:0*/ wr_controller__DOT__next_state;
        CData/*3:0*/ wr_controller__DOT__byteen_i_reg;
        CData/*3:0*/ wr_controller__DOT__counter_wire;
        CData/*0:0*/ wr_controller__DOT__counter_done;
        CData/*0:0*/ wr_controller__DOT__write_all;
        CData/*0:0*/ wr_controller__DOT__done_keep;
        CData/*0:0*/ wr_controller__DOT__counter_step;
        CData/*0:0*/ wr_controller__DOT____VdfgRegularize_h5cc42551_0_0;
        CData/*0:0*/ wr_controller__DOT__counter_offset_inst__DOT__clk;
        CData/*0:0*/ wr_controller__DOT__counter_offset_inst__DOT__rst_n;
        CData/*0:0*/ wr_controller__DOT__counter_offset_inst__DOT__start;
        CData/*4:0*/ wr_controller__DOT__counter_offset_inst__DOT__counter;
        CData/*0:0*/ wr_controller__DOT__counter_offset_inst__DOT__done;
        CData/*0:0*/ wr_controller__DOT__counter_offset_inst__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__clk;
        CData/*0:0*/ f_unit__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__in_ready;
        CData/*0:0*/ f_unit__DOT__in_valid;
        CData/*0:0*/ f_unit__DOT__write;
        CData/*0:0*/ f_unit__DOT__prefetch;
        CData/*0:0*/ f_unit__DOT__cache_hit;
        CData/*0:0*/ f_unit__DOT__cache_access_done;
        CData/*0:0*/ f_unit__DOT__out_valid;
        CData/*0:0*/ f_unit__DOT__out_ready;
        CData/*0:0*/ f_unit__DOT__trans_valid;
        CData/*0:0*/ f_unit__DOT__trans_done;
        CData/*0:0*/ f_unit__DOT__req_valid;
        CData/*0:0*/ f_unit__DOT__req_ready;
        CData/*0:0*/ f_unit__DOT__req_done;
        CData/*1:0*/ f_unit__DOT__cur_state;
        CData/*1:0*/ f_unit__DOT__next_state;
        CData/*7:0*/ f_unit__DOT__lifetime;
        CData/*7:0*/ f_unit__DOT__lifetime_p;
        CData/*3:0*/ f_unit__DOT__refresh;
        CData/*3:0*/ f_unit__DOT__start;
        CData/*3:0*/ f_unit__DOT__hit;
        CData/*3:0*/ f_unit__DOT__allocate;
        CData/*0:0*/ f_unit__DOT__empty;
        CData/*1:0*/ f_unit__DOT__empty_idx;
        CData/*1:0*/ f_unit__DOT__write_addr;
        CData/*0:0*/ f_unit__DOT__write_delete;
        CData/*0:0*/ f_unit__DOT__write_enable;
        CData/*0:0*/ f_unit__DOT__write_busy;
        CData/*3:0*/ f_unit__DOT__match_many;
        CData/*3:0*/ f_unit__DOT__match_single;
        CData/*1:0*/ f_unit__DOT__match_addr;
        CData/*0:0*/ f_unit__DOT__match;
        CData/*1:0*/ f_unit__DOT__rd_mem;
        CData/*0:0*/ f_unit__DOT__rd_cam;
        CData/*1:0*/ f_unit__DOT__erase_cam;
        CData/*0:0*/ f_unit__DOT__wr_cam;
        CData/*0:0*/ f_unit__DOT__read;
        CData/*0:0*/ f_unit__DOT__busy;
    };
    struct {
        CData/*0:0*/ f_unit__DOT__busy_p;
        CData/*0:0*/ f_unit__DOT__new_req;
        CData/*0:0*/ f_unit__DOT__write_keep;
        CData/*0:0*/ f_unit__DOT__cache_access_keep;
        CData/*0:0*/ f_unit__DOT__not_match_keep;
        CData/*0:0*/ f_unit__DOT__trans_done_keep;
        CData/*0:0*/ f_unit__DOT__req_done_keep;
        CData/*0:0*/ f_unit__DOT__rd_mem_done;
        CData/*0:0*/ f_unit__DOT__rd_cam_done;
        CData/*0:0*/ f_unit__DOT__erase_cam_done;
        CData/*0:0*/ f_unit__DOT__wr_cam_done;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_click;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_happend;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_done;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_click;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_happend;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_done;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_click;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_happend;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_done;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_click;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_happend;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_done;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_click;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_happend;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_done;
        CData/*0:0*/ f_unit__DOT__rd_mem_click;
        CData/*0:0*/ f_unit__DOT__erase_cam_click;
        CData/*0:0*/ f_unit__DOT__rd_cam_click;
        CData/*0:0*/ f_unit__DOT__wr_cam_click;
        CData/*0:0*/ f_unit__DOT__en;
        CData/*0:0*/ f_unit__DOT__wren;
        CData/*1:0*/ f_unit__DOT__mem_addr;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__0__KET____DOT__stream_counter__start;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__1__KET____DOT__stream_counter__start;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__2__KET____DOT__stream_counter__start;
        CData/*0:0*/ f_unit__DOT____Vcellinp__genblk1__BRA__3__KET____DOT__stream_counter__start;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__clk;
        CData/*7:0*/ f_unit__DOT__empty_tracker__DOT__sig_in;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__sig_out;
        CData/*1:0*/ f_unit__DOT__empty_tracker__DOT__idx;
        CData/*3:0*/ f_unit__DOT__empty_tracker__DOT__sig_processed;
        CData/*3:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__input_unencoded;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__output_valid;
        CData/*1:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__output_encoded;
        CData/*3:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__output_unencoded;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__out1;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__out2;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__valid1;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__valid2;
        CData/*1:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__input_unencoded;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_valid;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_encoded;
        CData/*1:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_unencoded;
        CData/*1:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__input_unencoded;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_valid;
        CData/*0:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_encoded;
        CData/*1:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_unencoded;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__clk;
    };
    struct {
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__rst;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__write_addr;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__write_delete;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__write_enable;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__write_busy;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__match_many;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__match_single;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__match_addr;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__match;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__clk;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__rst;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_addr;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_delete;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_enable;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_busy;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__match_many;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__match_single;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__match_addr;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__match;
        CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__state_reg;
        CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__state_next;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__set_bit;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__clear_bit;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__wr_en;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_addr_reg;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_addr_next;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_delete_reg;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_delete_next;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_busy_reg;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__match_many_raw;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__erase_ram_wr_en;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__match_data;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_data;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__input_unencoded;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__output_valid;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__output_encoded;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__output_unencoded;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__out1;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__out2;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__valid1;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__valid2;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__input_unencoded;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_valid;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_encoded;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_unencoded;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__input_unencoded;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_valid;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_encoded;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_unencoded;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__a_clk;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__a_we;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__a_din;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__a_dout;
        CData/*0:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__b_clk;
        CData/*1:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__b_we;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__b_din;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__b_dout;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__a_dout_reg;
        CData/*3:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__b_dout_reg;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__clk;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__rst;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__signal_in;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__signal_out;
        CData/*0:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__ff_m1;
    };
    struct {
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__clk;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__rst;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__signal_in;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__signal_out;
        CData/*0:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__ff_m1;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__clk;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__rst;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__signal_in;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__signal_out;
        CData/*0:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__ff_m1;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__clk;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__rst;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__signal_in;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__signal_out;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__ff_m1;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__clk;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__rst;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__signal_in;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__signal_out;
        CData/*0:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__ff_m1;
        CData/*0:0*/ f_unit__DOT__rd_mem_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__rd_mem_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__rd_mem_counter__DOT__start;
        CData/*0:0*/ f_unit__DOT__rd_mem_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__rd_mem_counter__DOT__done;
        CData/*0:0*/ f_unit__DOT__rd_mem_counter__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__rd_cam_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__rd_cam_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__rd_cam_counter__DOT__start;
        CData/*0:0*/ f_unit__DOT__rd_cam_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__rd_cam_counter__DOT__done;
        CData/*0:0*/ f_unit__DOT__rd_cam_counter__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__erase_cam_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__erase_cam_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__erase_cam_counter__DOT__start;
        CData/*1:0*/ f_unit__DOT__erase_cam_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__erase_cam_counter__DOT__done;
        CData/*0:0*/ f_unit__DOT__erase_cam_counter__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__wr_mem_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__wr_mem_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__wr_mem_counter__DOT__start;
        CData/*1:0*/ f_unit__DOT__wr_mem_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__wr_mem_counter__DOT__done;
        CData/*0:0*/ f_unit__DOT__wr_mem_counter__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__data_buffer__DOT__clk;
        CData/*0:0*/ f_unit__DOT__data_buffer__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__data_buffer__DOT__en;
        CData/*1:0*/ f_unit__DOT__data_buffer__DOT__in_addr;
        CData/*1:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__addra;
        CData/*0:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__clka;
        CData/*0:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__ena;
        CData/*0:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__rsta;
        CData/*0:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__regcea;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__0__KET____DOT__stream_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__0__KET____DOT__stream_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__0__KET____DOT__stream_counter__DOT__start;
        CData/*2:0*/ f_unit__DOT__genblk1__BRA__0__KET____DOT__stream_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__0__KET____DOT__stream_counter__DOT__done;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__0__KET____DOT__stream_counter__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__1__KET____DOT__stream_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__1__KET____DOT__stream_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__1__KET____DOT__stream_counter__DOT__start;
        CData/*2:0*/ f_unit__DOT__genblk1__BRA__1__KET____DOT__stream_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__1__KET____DOT__stream_counter__DOT__done;
    };
    struct {
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__1__KET____DOT__stream_counter__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__2__KET____DOT__stream_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__2__KET____DOT__stream_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__2__KET____DOT__stream_counter__DOT__start;
        CData/*2:0*/ f_unit__DOT__genblk1__BRA__2__KET____DOT__stream_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__2__KET____DOT__stream_counter__DOT__done;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__2__KET____DOT__stream_counter__DOT__done_w;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__3__KET____DOT__stream_counter__DOT__clk;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__3__KET____DOT__stream_counter__DOT__rst_n;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__3__KET____DOT__stream_counter__DOT__start;
        CData/*2:0*/ f_unit__DOT__genblk1__BRA__3__KET____DOT__stream_counter__DOT__counter;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__3__KET____DOT__stream_counter__DOT__done;
        CData/*0:0*/ f_unit__DOT__genblk1__BRA__3__KET____DOT__stream_counter__DOT__done_w;
        CData/*0:0*/ c_fsm__DOT__clk;
        CData/*0:0*/ c_fsm__DOT__rst_n;
        CData/*0:0*/ c_fsm__DOT__in_rw;
        CData/*3:0*/ c_fsm__DOT__in_source;
        CData/*2:0*/ c_fsm__DOT__in_opcode;
        CData/*1:0*/ c_fsm__DOT__in_mshr_id;
        CData/*0:0*/ c_fsm__DOT__in_valid;
        CData/*0:0*/ c_fsm__DOT__in_ready;
        CData/*3:0*/ c_fsm__DOT__out_source;
        CData/*2:0*/ c_fsm__DOT__out_opcode;
        CData/*0:0*/ c_fsm__DOT__out_valid;
        CData/*0:0*/ c_fsm__DOT__out_ready;
        CData/*0:0*/ c_fsm__DOT__fw_rw;
        CData/*0:0*/ c_fsm__DOT__fw_valid;
        CData/*0:0*/ c_fsm__DOT__fw_ready;
        CData/*0:0*/ c_fsm__DOT__ib_valid;
        CData/*0:0*/ c_fsm__DOT__ib_ready;
        CData/*0:0*/ c_fsm__DOT__fsm_accessed;
        CData/*0:0*/ c_fsm__DOT__fsm_hit;
        CData/*0:0*/ c_fsm__DOT__mshr_fin_valid;
        CData/*0:0*/ c_fsm__DOT__mshr_fin_is_hit;
        CData/*1:0*/ c_fsm__DOT__mshr_fin_id;
        CData/*0:0*/ c_fsm__DOT__miss_trigger;
        CData/*0:0*/ c_fsm__DOT__cur_state;
        CData/*0:0*/ c_fsm__DOT__next_state;
        CData/*3:0*/ c_fsm__DOT__source_keep;
        CData/*2:0*/ c_fsm__DOT__opcode_keep;
        CData/*1:0*/ c_fsm__DOT__mshr_id_keep;
        CData/*0:0*/ c_fsm__DOT__write_keep;
        CData/*3:0*/ c_fsm__DOT__word_idx;
        CData/*0:0*/ mshr_inst__DOT__clk;
        CData/*0:0*/ mshr_inst__DOT__rst_n;
        CData/*0:0*/ mshr_inst__DOT__alloc_valid;
        CData/*3:0*/ mshr_inst__DOT__alloc_source;
        CData/*2:0*/ mshr_inst__DOT__alloc_opcode;
        CData/*3:0*/ mshr_inst__DOT__alloc_byteen;
        CData/*0:0*/ mshr_inst__DOT__alloc_ready;
        CData/*1:0*/ mshr_inst__DOT__alloc_id;
        CData/*0:0*/ mshr_inst__DOT__alloc_match;
        CData/*1:0*/ mshr_inst__DOT__alloc_match_id;
        CData/*0:0*/ mshr_inst__DOT__fin_valid;
        CData/*1:0*/ mshr_inst__DOT__fin_id;
        CData/*0:0*/ mshr_inst__DOT__fin_is_hit;
        CData/*0:0*/ mshr_inst__DOT__fin_is_coalesced;
        CData/*1:0*/ mshr_inst__DOT__fin_prev_id;
        CData/*0:0*/ mshr_inst__DOT__fill_valid;
        CData/*1:0*/ mshr_inst__DOT__fill_id;
        CData/*0:0*/ mshr_inst__DOT__deq_valid;
        CData/*0:0*/ mshr_inst__DOT__deq_ready;
        CData/*3:0*/ mshr_inst__DOT__deq_source;
        CData/*2:0*/ mshr_inst__DOT__deq_opcode;
    };
    struct {
        CData/*3:0*/ mshr_inst__DOT__deq_byteen;
        CData/*1:0*/ mshr_inst__DOT__deq_id;
        CData/*0:0*/ mshr_inst__DOT__empty;
        CData/*0:0*/ mshr_inst__DOT__full;
        CData/*3:0*/ mshr_inst__DOT__valid_table;
        CData/*3:0*/ mshr_inst__DOT__next_table;
        CData/*3:0*/ mshr_inst__DOT__addr_matches;
        CData/*3:0*/ mshr_inst__DOT__tail_candidates;
        CData/*1:0*/ mshr_inst__DOT__tail_idx;
        CData/*3:0*/ mshr_inst__DOT__free_slots;
        CData/*1:0*/ mshr_inst__DOT__next_free_id;
        CData/*0:0*/ mshr_inst__DOT__free_slot_exists;
        CData/*1:0*/ mshr_inst__DOT__deq_ptr_q;
        CData/*1:0*/ mshr_inst__DOT__deq_ptr_d;
        CData/*0:0*/ mshr_inst__DOT__deq_active_q;
        CData/*0:0*/ mshr_inst__DOT__deq_active_d;
        CData/*0:0*/ mshr_inst__DOT__alloc_fire;
        CData/*0:0*/ mshr_inst__DOT__deq_fire;
        CData/*3:0*/ mshr_inst__DOT__tail_encoder__DOT__input_unencoded;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__output_valid;
        CData/*1:0*/ mshr_inst__DOT__tail_encoder__DOT__output_encoded;
        CData/*3:0*/ mshr_inst__DOT__tail_encoder__DOT__output_unencoded;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__out1;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__out2;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__valid1;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__valid2;
        CData/*1:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__input_unencoded;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_valid;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_encoded;
        CData/*1:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_unencoded;
        CData/*1:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__input_unencoded;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_valid;
        CData/*0:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_encoded;
        CData/*1:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_unencoded;
        CData/*3:0*/ mshr_inst__DOT__free_slot_encoder__DOT__input_unencoded;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__output_valid;
        CData/*1:0*/ mshr_inst__DOT__free_slot_encoder__DOT__output_encoded;
        CData/*3:0*/ mshr_inst__DOT__free_slot_encoder__DOT__output_unencoded;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__out1;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__out2;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__valid1;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__valid2;
        CData/*1:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__input_unencoded;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_valid;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_encoded;
        CData/*1:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__output_unencoded;
        CData/*1:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__input_unencoded;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_valid;
        CData/*0:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_encoded;
        CData/*1:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__output_unencoded;
        CData/*0:0*/ d_array__DOT__clk;
        CData/*0:0*/ d_array__DOT__rst_n;
        CData/*0:0*/ d_array__DOT__busy;
        CData/*0:0*/ d_array__DOT__valid;
        CData/*0:0*/ d_array__DOT__write;
        CData/*3:0*/ d_array__DOT__in_byteen;
        CData/*3:0*/ d_array__DOT__way;
        CData/*0:0*/ d_array__DOT__write_all;
        CData/*3:0*/ d_array__DOT__word_idx;
        CData/*0:0*/ d_array__DOT__valid_prev;
        CData/*0:0*/ d_array__DOT__counter_done;
        CData/*0:0*/ d_array__DOT__write_prev;
        CData/*0:0*/ d_array__DOT__write_click;
        CData/*0:0*/ d_array__DOT__D_FF_valid__DOT__clk;
    };
    struct {
        CData/*0:0*/ d_array__DOT__D_FF_valid__DOT__rst_n;
        CData/*0:0*/ d_array__DOT__D_FF_valid__DOT__set;
        CData/*0:0*/ d_array__DOT__D_FF_valid__DOT__din;
        CData/*0:0*/ d_array__DOT__D_FF_valid__DOT__dout;
        CData/*0:0*/ d_array__DOT__D_FF_valid__DOT__data;
        CData/*0:0*/ d_array__DOT__latency_counter__DOT__clk;
        CData/*0:0*/ d_array__DOT__latency_counter__DOT__rst_n;
        CData/*0:0*/ d_array__DOT__latency_counter__DOT__start;
        CData/*1:0*/ d_array__DOT__latency_counter__DOT__counter;
        CData/*0:0*/ d_array__DOT__latency_counter__DOT__done;
        CData/*0:0*/ d_array__DOT__latency_counter__DOT__done_w;
        CData/*0:0*/ sec_address_translator__DOT__clk;
        CData/*0:0*/ sec_address_translator__DOT__rst_n;
        CData/*0:0*/ sec_address_translator__DOT__cfg_load;
        CData/*3:0*/ sec_address_translator__DOT__cfg_low_bound;
        CData/*3:0*/ sec_address_translator__DOT__cfg_high_bound;
        CData/*0:0*/ sec_address_translator__DOT__cfg_en;
        CData/*0:0*/ sec_address_translator__DOT__in_valid;
        CData/*0:0*/ sec_address_translator__DOT__in_ready;
        CData/*0:0*/ sec_address_translator__DOT__in_done;
        CData/*3:0*/ sec_address_translator__DOT__rng_val;
        CData/*0:0*/ sec_address_translator__DOT____Vcellinp__num_gen__valid;
        CData/*0:0*/ sec_address_translator__DOT__num_gen__DOT__clk;
        CData/*0:0*/ sec_address_translator__DOT__num_gen__DOT__rst_n;
        CData/*0:0*/ sec_address_translator__DOT__num_gen__DOT__valid;
        CData/*0:0*/ sec_address_translator__DOT__num_gen__DOT__request;
        CData/*3:0*/ sec_address_translator__DOT__num_gen__DOT__out;
        CData/*0:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__clk;
        CData/*0:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__rst_n;
        CData/*0:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__en;
        CData/*3:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__low_bound;
        CData/*3:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__high_bound;
        CData/*3:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__rng_val;
        CData/*0:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__valid;
        CData/*0:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__done;
        CData/*0:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__done_ff;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_0;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_1;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_2;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_3;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_4;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_5;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_6;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_7;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_8;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_9;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_10;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_11;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_12;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_13;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_14;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_15;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_16;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_17;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_18;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_19;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_20;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_21;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_22;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_23;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_24;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_25;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_26;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_27;
    };
    struct {
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_28;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_29;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_30;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_31;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_32;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_33;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_34;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_35;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_36;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_37;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_38;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_39;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_40;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_41;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_42;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_43;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_44;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_45;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_46;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_47;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_48;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_49;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_50;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_51;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_52;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_53;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_54;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_55;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_56;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_57;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_58;
        CData/*7:0*/ __VdfgRegularize_h953fb8a2_0_59;
        CData/*0:0*/ __Vdly__f_unit__DOT__req_done_keep;
        SData/*15:0*/ cache_write_strb;
        SData/*15:0*/ wr_controller__DOT__cache_write_strb;
        SData/*15:0*/ d_array__DOT__en;
        VL_IN(cfg_data_in,31,0);
        VL_OUT(cfg_data_out,31,0);
        VL_IN(in_addr,31,0);
        VL_IN(in_data,31,0);
        VL_OUT(out_addr,31,0);
        VL_OUT(out_data,31,0);
        VL_OUT(read_addr,31,0);
        VL_IN(read_data,31,0);
        VL_OUT(write_addr,31,0);
        VL_OUT(write_data,31,0);
        VlWide<6>/*167:0*/ load_val;
        IData/*31:0*/ req_addr;
        VlWide<16>/*511:0*/ req_data;
        VlWide<16>/*511:0*/ arr_data;
        IData/*31:0*/ cache_write_addr;
        VlWide<16>/*511:0*/ cache_write_data;
        IData/*31:0*/ fsm_addr;
        IData/*31:0*/ fsm_data;
        IData/*31:0*/ return_addr;
        VlWide<16>/*511:0*/ return_data;
        IData/*31:0*/ trans_out_addr;
        IData/*31:0*/ trans_in_addr;
        IData/*31:0*/ fsm_out_addr;
        IData/*31:0*/ fsm_out_data;
        IData/*31:0*/ mshr_deq_addr;
        IData/*31:0*/ mshr_deq_data;
        IData/*31:0*/ refill_word_data;
        VlWide<16>/*511:0*/ data;
    };
    struct {
        IData/*31:0*/ addr;
        IData/*31:0*/ reg_file__DOT__in_data;
        IData/*31:0*/ reg_file__DOT__out_data;
        VlWide<6>/*167:0*/ reg_file__DOT__load_val;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_0__DOT__din;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_0__DOT__dout;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_0__DOT__data;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_1__DOT__din;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_1__DOT__dout;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_1__DOT__data;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_2__DOT__din;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_2__DOT__dout;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_2__DOT__data;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_3__DOT__din;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_3__DOT__dout;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_3__DOT__data;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_4__DOT__din;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_4__DOT__dout;
        IData/*31:0*/ reg_file__DOT__D_FF_l_va_4__DOT__data;
        IData/*31:0*/ rd_controller__DOT__cache_read_addr;
        VlWide<16>/*511:0*/ rd_controller__DOT__cache_read_data;
        IData/*31:0*/ rd_controller__DOT__mem_read_addr;
        IData/*31:0*/ rd_controller__DOT__mem_read_data;
        IData/*31:0*/ rd_controller__DOT__addr_i_reg;
        IData/*31:0*/ rd_controller__DOT__mem_read_o_addr;
        IData/*31:0*/ wr_controller__DOT__cache_write_addr;
        VlWide<16>/*511:0*/ wr_controller__DOT__cache_write_data;
        IData/*31:0*/ wr_controller__DOT__mem_write_addr;
        IData/*31:0*/ wr_controller__DOT__mem_write_data;
        IData/*31:0*/ wr_controller__DOT__addr_i_reg;
        VlWide<16>/*511:0*/ wr_controller__DOT__data_in_i_reg;
        IData/*31:0*/ f_unit__DOT__in_addr;
        IData/*31:0*/ f_unit__DOT__in_data;
        IData/*31:0*/ f_unit__DOT__out_addr;
        VlWide<16>/*511:0*/ f_unit__DOT__out_data;
        IData/*31:0*/ f_unit__DOT__trans_out_addr;
        IData/*31:0*/ f_unit__DOT__trans_in_addr;
        IData/*31:0*/ f_unit__DOT__req_addr;
        VlWide<16>/*511:0*/ f_unit__DOT__req_data;
        IData/*25:0*/ f_unit__DOT__write_data;
        IData/*25:0*/ f_unit__DOT__compare_data;
        IData/*31:0*/ f_unit__DOT__prev_addr;
        IData/*31:0*/ f_unit__DOT__in_data_keep;
        VlWide<16>/*511:0*/ f_unit__DOT__buffer_data;
        VlWide<16>/*511:0*/ f_unit__DOT__mem_in_data;
        VlWide<16>/*511:0*/ f_unit__DOT__mem_out_data;
        IData/*31:0*/ f_unit__DOT__unnamedblk1__DOT__j;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__write_data;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__compare_data;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_data;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__compare_data;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__compare_data_padded;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_data_padded;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__count_reg;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__count_next;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__ram_addr;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_data_padded_reg;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__write_data_padded_next;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__erase_data;
        IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__i;
        IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__k;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__a_addr;
        IData/*25:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__b_addr;
        IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__i;
    };
    struct {
        IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__j;
        VlWide<16>/*511:0*/ f_unit__DOT__data_buffer__DOT__in_data;
        VlWide<16>/*511:0*/ f_unit__DOT__data_buffer__DOT__out_data;
        VlWide<16>/*511:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__dina;
        VlWide<16>/*511:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__douta;
        VlWide<16>/*511:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__ram_data;
        IData/*31:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__init_bram_to_zero__DOT__ram_index;
        IData/*31:0*/ c_fsm__DOT__in_addr;
        IData/*31:0*/ c_fsm__DOT__in_data;
        IData/*31:0*/ c_fsm__DOT__out_addr;
        IData/*31:0*/ c_fsm__DOT__out_data;
        IData/*31:0*/ c_fsm__DOT__fw_addr;
        IData/*31:0*/ c_fsm__DOT__fw_data;
        IData/*31:0*/ c_fsm__DOT__ib_addr;
        VlWide<16>/*511:0*/ c_fsm__DOT__ib_data;
        IData/*31:0*/ c_fsm__DOT__addr_keep;
        IData/*31:0*/ c_fsm__DOT__data_keep;
        IData/*31:0*/ mshr_inst__DOT__alloc_addr;
        IData/*31:0*/ mshr_inst__DOT__alloc_data;
        IData/*31:0*/ mshr_inst__DOT__fill_addr;
        IData/*31:0*/ mshr_inst__DOT__deq_addr;
        IData/*31:0*/ mshr_inst__DOT__deq_data;
        IData/*25:0*/ mshr_inst__DOT__incoming_line_addr;
        IData/*31:0*/ d_array__DOT__addr;
        VlWide<16>/*511:0*/ d_array__DOT__data;
        VlWide<16>/*511:0*/ d_array__DOT__out_data;
        IData/*31:0*/ d_array__DOT__in_addr;
        VlWide<16>/*511:0*/ d_array__DOT__in_data;
        VlWide<6>/*167:0*/ sec_address_translator__DOT__cfg_load_val;
        IData/*31:0*/ sec_address_translator__DOT__in_raw_addr;
        IData/*31:0*/ sec_address_translator__DOT__in_trans_addr;
        VlWide<6>/*167:0*/ sec_address_translator__DOT__num_gen__DOT__in;
        IData/*31:0*/ sec_address_translator__DOT__num_gen__DOT__out_w;
        VlWide<6>/*167:0*/ sec_address_translator__DOT__num_gen__DOT__lfsr_reg;
        IData/*31:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__addr;
        IData/*31:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__out;
        IData/*31:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__add_addr;
        IData/*31:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__cal_addr;
        IData/*31:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__out_ff;
        IData/*31:0*/ __VdfgRegularize_h953fb8a2_0_60;
        QData/*63:0*/ f_unit__DOT__data_buffer__DOT__wren;
        QData/*63:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__wea;
        QData/*63:0*/ d_array__DOT__byte_mask;
        VlUnpacked<CData/*3:0*/, 1> f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__match_raw_out;
        VlUnpacked<IData/*25:0*/, 4> f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__erase_ram;
        VlUnpacked<CData/*3:0*/, 67108864> f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__mem;
        VlUnpacked<VlWide<16>/*511:0*/, 4> f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__BRAM;
        VlUnpacked<IData/*25:0*/, 4> mshr_inst__DOT__addr_table;
        VlUnpacked<CData/*3:0*/, 4> mshr_inst__DOT__source_table;
        VlUnpacked<CData/*2:0*/, 4> mshr_inst__DOT__opcode_table;
        VlUnpacked<CData/*3:0*/, 4> mshr_inst__DOT__byteen_table;
        VlUnpacked<IData/*31:0*/, 4> mshr_inst__DOT__data_table;
        VlUnpacked<CData/*1:0*/, 4> mshr_inst__DOT__next_index;
        VlUnpacked<QData/*63:0*/, 16> d_array__DOT__wren;
        VlUnpacked<VlWide<16>/*511:0*/, 16> d_array__DOT__out_data_array;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__STATE_INIT = 0U;
    static constexpr CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__STATE_IDLE = 1U;
    static constexpr CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__STATE_DELETE_1 = 2U;
    static constexpr CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__STATE_DELETE_2 = 3U;
    static constexpr CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__STATE_WRITE_1 = 4U;
    static constexpr CData/*2:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__STATE_WRITE_2 = 5U;
    static constexpr CData/*7:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__INIT_FILE = 0U;
    static constexpr CData/*0:0*/ c_fsm__DOT__STATE_IDLE = 0U;
    static constexpr CData/*0:0*/ c_fsm__DOT__STATE_COMPARE = 1U;
    static constexpr IData/*31:0*/ TOTAL_SIZE = 0x00080000U;
    static constexpr IData/*31:0*/ ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ DATA_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ DATA_ELEMENTS = 0x00000040U;
    static constexpr IData/*31:0*/ SIZE = 4U;
    static constexpr IData/*31:0*/ LATENCY = 2U;
    static constexpr IData/*31:0*/ BOUND_SIZE = 4U;
    static constexpr IData/*31:0*/ QUEUE_SIZE = 0U;
    static constexpr IData/*31:0*/ NUM_WAYS = 0x00000010U;
    static constexpr IData/*31:0*/ SET_REPLACEMENT_POLICY = 0x4e4d5255U;
    static constexpr IData/*31:0*/ _BLOCK_SIZE = 0x00000200U;
    static constexpr IData/*31:0*/ _NUM_LINES = 0x00000040U;
    static constexpr IData/*31:0*/ _OFFSET_BITS = 6U;
    static constexpr IData/*31:0*/ _LINE_BITS = 6U;
    static constexpr IData/*31:0*/ _TAG_BITS = 0x00000014U;
    static constexpr IData/*31:0*/ _NUM_TRANSFER = 0x00000010U;
    static constexpr IData/*31:0*/ _TRANSFER_BITS = 4U;
    static constexpr IData/*31:0*/ _WAY_BITS = 4U;
    static constexpr IData/*31:0*/ reg_file__DOT__BOUND_SIZE = 4U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_write = 0U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_secure = 4U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_low_bound = 8U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_high_bound = 0x0000000cU;
    static constexpr IData/*31:0*/ reg_file__DOT__en_prefetch = 0x00000010U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_load_val_0 = 0x00000014U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_load_val_1 = 0x00000018U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_load_val_2 = 0x0000001cU;
    static constexpr IData/*31:0*/ reg_file__DOT__en_load_val_3 = 0x00000020U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_load_val_4 = 0x00000024U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_load_val_5 = 0x00000028U;
    static constexpr IData/*31:0*/ reg_file__DOT__en_load_val = 0x0000002cU;
    static constexpr IData/*31:0*/ reg_file__DOT__load_val_edge__DOT__EDGE = 0U;
    static constexpr IData/*31:0*/ reg_file__DOT__load_val_edge__DOT__POS_EDGE = 0U;
    static constexpr IData/*31:0*/ reg_file__DOT__load_val_edge__DOT__NEG_EDGE = 1U;
    static constexpr IData/*31:0*/ reg_file__DOT__load_val_edge__DOT__ANY_EDGE = 2U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_write__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_secure__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_l_b__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_h_b__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_pf__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_l_va_0__DOT__SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_l_va_1__DOT__SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_l_va_2__DOT__SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_l_va_3__DOT__SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_l_va_4__DOT__SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_l_va_5__DOT__SIZE = 8U;
    static constexpr IData/*31:0*/ reg_file__DOT__D_FF_addr__DOT__SIZE = 6U;
    static constexpr IData/*31:0*/ rd_controller__DOT__ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ rd_controller__DOT__DATA_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ rd_controller__DOT__DATA_ELEMENTS = 0x00000040U;
    static constexpr IData/*31:0*/ rd_controller__DOT__TOTAL_SIZE = 0x00080000U;
    static constexpr IData/*31:0*/ rd_controller__DOT__LATENCY = 2U;
    static constexpr IData/*31:0*/ rd_controller__DOT__NUM_WAYS = 0x00000010U;
    static constexpr IData/*31:0*/ rd_controller__DOT__SET_REPLACEMENT_POLICY = 0x4e4d5255U;
    static constexpr IData/*31:0*/ rd_controller__DOT___BLOCK_SIZE = 0x00000200U;
    static constexpr IData/*31:0*/ rd_controller__DOT___NUM_LINES = 0x00000040U;
    static constexpr IData/*31:0*/ rd_controller__DOT___OFFSET_BITS = 6U;
    static constexpr IData/*31:0*/ rd_controller__DOT___LINE_BITS = 6U;
    static constexpr IData/*31:0*/ rd_controller__DOT___TAG_BITS = 0x00000014U;
    static constexpr IData/*31:0*/ rd_controller__DOT___NUM_TRANSFER = 0x00000010U;
    static constexpr IData/*31:0*/ rd_controller__DOT___TRANSFER_BITS = 4U;
    static constexpr IData/*31:0*/ rd_controller__DOT___COUNT_LIMIT = 0x0000000fU;
    static constexpr IData/*31:0*/ rd_controller__DOT__STATE_IDLE = 0U;
    static constexpr IData/*31:0*/ rd_controller__DOT__STATE_MEM_RD_WAIT = 1U;
    static constexpr IData/*31:0*/ rd_controller__DOT__counter_offset_inst__DOT__COUNT_LIMIT = 0x0000000fU;
    static constexpr IData/*31:0*/ wr_controller__DOT__ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ wr_controller__DOT__DATA_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ wr_controller__DOT__DATA_ELEMENTS = 0x00000040U;
    static constexpr IData/*31:0*/ wr_controller__DOT__TOTAL_SIZE = 0x00080000U;
    static constexpr IData/*31:0*/ wr_controller__DOT__LATENCY = 2U;
    static constexpr IData/*31:0*/ wr_controller__DOT__NUM_WAYS = 0x00000010U;
    static constexpr IData/*31:0*/ wr_controller__DOT__SET_REPLACEMENT_POLICY = 0x4e4d5255U;
    static constexpr IData/*31:0*/ wr_controller__DOT___BLOCK_SIZE = 0x00000200U;
    static constexpr IData/*31:0*/ wr_controller__DOT___NUM_LINES = 0x00000040U;
    static constexpr IData/*31:0*/ wr_controller__DOT___OFFSET_BITS = 6U;
    static constexpr IData/*31:0*/ wr_controller__DOT___LINE_BITS = 6U;
    static constexpr IData/*31:0*/ wr_controller__DOT___TAG_BITS = 0x00000014U;
    static constexpr IData/*31:0*/ wr_controller__DOT___NUM_TRANSFER = 0x00000010U;
    static constexpr IData/*31:0*/ wr_controller__DOT___TRANSFER_BITS = 4U;
    static constexpr IData/*31:0*/ wr_controller__DOT__STATE_IDLE = 0U;
    static constexpr IData/*31:0*/ wr_controller__DOT__STATE_BUSY = 1U;
    static constexpr IData/*31:0*/ wr_controller__DOT__counter_offset_inst__DOT__COUNT_LIMIT = 0x0000000fU;
    static constexpr IData/*31:0*/ f_unit__DOT__TOTAL_SIZE = 0x00080000U;
    static constexpr IData/*31:0*/ f_unit__DOT__ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ f_unit__DOT__DATA_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ f_unit__DOT__DATA_ELEMENTS = 0x00000040U;
    static constexpr IData/*31:0*/ f_unit__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__LATENCY = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__NUM_WAYS = 0x00000010U;
    static constexpr IData/*31:0*/ f_unit__DOT__SET_REPLACEMENT_POLICY = 0x4e4d5255U;
    static constexpr IData/*31:0*/ f_unit__DOT___BLOCK_SIZE = 0x00000200U;
    static constexpr IData/*31:0*/ f_unit__DOT___NUM_LINES = 0x00000040U;
    static constexpr IData/*31:0*/ f_unit__DOT___OFFSET_BITS = 6U;
    static constexpr IData/*31:0*/ f_unit__DOT___LINE_BITS = 6U;
    static constexpr IData/*31:0*/ f_unit__DOT___TAG_BITS = 0x00000014U;
    static constexpr IData/*31:0*/ f_unit__DOT___NUM_TRANSFER = 0x00000010U;
    static constexpr IData/*31:0*/ f_unit__DOT___TRANSFER_BITS = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__STATE_IDLE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__STATE_PREFETCH = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__STATE_COMPARE = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__STATE_FETCH = 3U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__WIDTH = 4U;
    static constexpr IData/*23:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__LSB_PRIORITY = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__W1 = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__W2 = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__WIDTH = 2U;
    static constexpr IData/*23:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__LSB_PRIORITY = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__WIDTH = 2U;
    static constexpr IData/*23:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__LSB_PRIORITY = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__empty_tracker__DOT__idx_tracker__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__DATA_WIDTH = 0x0000001aU;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__ADDR_WIDTH = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__CAM_STYLE = 0x4252414dU;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__SLICE_WIDTH = 0x0000001aU;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__DATA_WIDTH = 0x0000001aU;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__ADDR_WIDTH = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__SLICE_WIDTH = 0x0000001aU;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__SLICE_COUNT = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__RAM_DEPTH = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__W = 0x0000001aU;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__WIDTH = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__W1 = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__W2 = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__WIDTH = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__WIDTH = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__priority_encoder_inst__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__DATA_WIDTH = 4U;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__ADDR_WIDTH = 0x0000001aU;
    static constexpr IData/*31:0*/ f_unit__DOT__tag_buffer__DOT__genblk1__DOT__cam_inst__DOT__slice__BRA__0__KET____DOT__ram_inst__DOT__RAM_DEPTH_SAFE = 0x04000000U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__POS_EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__NEG_EDGE = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_rd_cam_edge__DOT__ANY_EDGE = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__POS_EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__NEG_EDGE = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_erase_edge__DOT__ANY_EDGE = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__POS_EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__NEG_EDGE = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_prefetch_wr_cam_edge__DOT__ANY_EDGE = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__POS_EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__NEG_EDGE = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_cam_edge__DOT__ANY_EDGE = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__POS_EDGE = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__NEG_EDGE = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__w_compare_rd_mem_edge__DOT__ANY_EDGE = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__rd_mem_counter__DOT__COUNT_LIMIT = 1U;
    static constexpr IData/*31:0*/ f_unit__DOT__rd_cam_counter__DOT__COUNT_LIMIT = 0U;
    static constexpr IData/*31:0*/ f_unit__DOT__erase_cam_counter__DOT__COUNT_LIMIT = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__wr_mem_counter__DOT__COUNT_LIMIT = 2U;
    static constexpr IData/*31:0*/ f_unit__DOT__data_buffer__DOT__MEM_WIDTH = 0x00000200U;
    static constexpr IData/*31:0*/ f_unit__DOT__data_buffer__DOT__MEM_DEPTH = 4U;
    static constexpr VlWide<3>/*79:0*/ f_unit__DOT__data_buffer__DOT__MEM_TYPE = {{
        0x5f4c4f57, 0x4c494e58, 0x00005849
    }};
    static constexpr IData/*31:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__RAM_WIDTH = 0x00000200U;
    static constexpr IData/*31:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__RAM_DEPTH = 4U;
    static constexpr VlWide<3>/*87:0*/ f_unit__DOT__data_buffer__DOT__genblk1__DOT__xilinx_single_port_ram_no_change__DOT__RAM_PERFORMANCE = {{
        0x454e4359, 0x5f4c4154, 0x004c4f57
    }};
    static constexpr IData/*31:0*/ f_unit__DOT__genblk1__BRA__0__KET____DOT__stream_counter__DOT__COUNT_LIMIT = 3U;
    static constexpr IData/*31:0*/ f_unit__DOT__genblk1__BRA__1__KET____DOT__stream_counter__DOT__COUNT_LIMIT = 3U;
    static constexpr IData/*31:0*/ f_unit__DOT__genblk1__BRA__2__KET____DOT__stream_counter__DOT__COUNT_LIMIT = 3U;
    static constexpr IData/*31:0*/ f_unit__DOT__genblk1__BRA__3__KET____DOT__stream_counter__DOT__COUNT_LIMIT = 3U;
    static constexpr IData/*31:0*/ c_fsm__DOT__ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ c_fsm__DOT__DATA_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ c_fsm__DOT__DATA_ELEMENTS = 0x00000040U;
    static constexpr IData/*31:0*/ c_fsm__DOT__TOTAL_SIZE = 0x00080000U;
    static constexpr IData/*31:0*/ c_fsm__DOT__LATENCY = 2U;
    static constexpr IData/*31:0*/ c_fsm__DOT__NUM_WAYS = 0x00000010U;
    static constexpr IData/*31:0*/ c_fsm__DOT__SET_REPLACEMENT_POLICY = 0x4e4d5255U;
    static constexpr IData/*31:0*/ c_fsm__DOT___BLOCK_SIZE = 0x00000200U;
    static constexpr IData/*31:0*/ c_fsm__DOT___NUM_LINES = 0x00000040U;
    static constexpr IData/*31:0*/ c_fsm__DOT___OFFSET_BITS = 6U;
    static constexpr IData/*31:0*/ c_fsm__DOT___LINE_BITS = 6U;
    static constexpr IData/*31:0*/ c_fsm__DOT___TAG_BITS = 0x00000014U;
    static constexpr IData/*31:0*/ c_fsm__DOT___NUM_TRANSFER = 0x00000010U;
    static constexpr IData/*31:0*/ c_fsm__DOT___TRANSFER_BITS = 4U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__MSHR_SIZE = 4U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__DATA_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__SOURCE_WIDTH = 4U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__LINE_OFFSET_BITS = 6U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__LINE_ADDR_WIDTH = 0x0000001aU;
    static constexpr IData/*31:0*/ mshr_inst__DOT__MSHR_ADDR_WIDTH = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__WIDTH = 4U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__W1 = 4U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__W2 = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__WIDTH = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__WIDTH = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__tail_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__WIDTH = 4U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__W1 = 4U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__W2 = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__WIDTH = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst1__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__WIDTH = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__LSB_PRIORITY = 0x48494748U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W1 = 2U;
    static constexpr IData/*31:0*/ mshr_inst__DOT__free_slot_encoder__DOT__genblk1__DOT__priority_encoder_inst2__DOT__W2 = 1U;
    static constexpr IData/*31:0*/ d_array__DOT__ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ d_array__DOT__DATA_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ d_array__DOT__DATA_ELEMENTS = 0x00000040U;
    static constexpr IData/*31:0*/ d_array__DOT__TOTAL_SIZE = 0x00080000U;
    static constexpr IData/*31:0*/ d_array__DOT__LATENCY = 2U;
    static constexpr IData/*31:0*/ d_array__DOT__NUM_WAYS = 0x00000010U;
    static constexpr IData/*31:0*/ d_array__DOT__SET_REPLACEMENT_POLICY = 0x4e4d5255U;
    static constexpr IData/*31:0*/ d_array__DOT___BLOCK_SIZE = 0x00000200U;
    static constexpr IData/*31:0*/ d_array__DOT___NUM_LINES = 0x00000040U;
    static constexpr IData/*31:0*/ d_array__DOT___OFFSET_BITS = 6U;
    static constexpr IData/*31:0*/ d_array__DOT___LINE_BITS = 6U;
    static constexpr IData/*31:0*/ d_array__DOT___TAG_BITS = 0x00000014U;
    static constexpr IData/*31:0*/ d_array__DOT___NUM_TRANSFER = 0x00000010U;
    static constexpr IData/*31:0*/ d_array__DOT___TRANSFER_BITS = 4U;
    static constexpr IData/*31:0*/ d_array__DOT___WAY_BITS = 4U;
    static constexpr IData/*31:0*/ d_array__DOT___BYTES_PER_BLOCK = 0x00000040U;
    static constexpr IData/*31:0*/ d_array__DOT___BYTES_PER_WORD = 4U;
    static constexpr IData/*31:0*/ d_array__DOT__D_FF_valid__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ d_array__DOT__latency_counter__DOT__COUNT_LIMIT = 2U;
    static constexpr IData/*31:0*/ sec_address_translator__DOT__BOUND_SIZE = 4U;
    static constexpr IData/*31:0*/ sec_address_translator__DOT__ADDR_SIZE = 0x00000020U;
    static constexpr IData/*31:0*/ sec_address_translator__DOT__num_gen__DOT__BOUND_SIZE = 4U;
    static constexpr IData/*31:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__BOUND_SIZE = 4U;
    static constexpr IData/*31:0*/ sec_address_translator__DOT__rand_fill_engine__DOT__ADDR_SIZE = 0x00000020U;
    static const std::string f_unit__DOT__empty_tracker__DOT__LSB_PRIORITY;

    // CONSTRUCTORS
    Vtop_cache_controller_nb(Vtop__Syms* symsp, const char* v__name);
    ~Vtop_cache_controller_nb();
    VL_UNCOPYABLE(Vtop_cache_controller_nb);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
